### ISSUE TITLE
Interface: Submit Rule is missing options

### ISSUE THREAD

**Issue by wei9528** [digi-serve/plugin_ABDesigner#100]
**To Reproduce**
1. Go to https://staging2.appdevdesigns.net, select a form, click Settings in the Submit Rules.
![Untitled 2](https://user-images.githubusercontent.com/67583075/204996287-e482e394-a734-46ea-9b3e-b2dc832f92dc.png)
Expected Result:
![2](https://user-images.githubusercontent.com/67583075/204996439-cf9797ab-fc86-45b4-ba4d-8320e51698e7.png)

**Comment by wongpratan** [comment]
https://github.com/digi-serve/plugin_ABDesigner/commit/2d8d61b2d1b37bcd8fc98295ffe2e6ae7e4ee1ec
