### ISSUE TITLE
Interface: Hiding columns is not working

### ISSUE THREAD

**Issue by wei9528** [digi-serve/plugin_ABDesigner#101]
**To Reproduce**
1. Go to https://staging2.appdevdesigns.net/home
2. Select a grid page, try to hide some fields, check the grid page or UI page, the hiding operation is not in effect
![Untitled 2](https://user-images.githubusercontent.com/67583075/204998098-dacd8d3f-f959-48b2-bc7d-780d43bb7988.png)

**Comment by wongpratan** [comment]
`settings.hiddenFields` is overwrite by `settings.objectWorkspace`
https://github.com/digi-serve/appbuilder_class_core/blob/ABDesigner/views/ABViewGridCore.js#L305

I don't sure is it the user requirement or a bug ?
