### ISSUE TITLE
Export an App with a Version

### ISSUE THREAD

**Issue by nh758** [digi-serve/plugin_ABDesigner#108]
> “As a builder, I export an app with version details, so that I can track my changes.”

## Requirements
1. Before exporting show a form with version details (number, summary and release notes).
2. The version details are added to the JSON and exported.

### Tasks
- [ ] Create UI for adding version
- [x] Add version number in the definitions

- [ ] Write Documentation

## Reference
![image](https://user-images.githubusercontent.com/10155226/210314467-c4b3d3a5-3a4f-423a-8720-0bf375858eed.png)
https://snippet.webix.com/c4v7q2xh

**Comment by Achoobert** [comment]
![image](https://user-images.githubusercontent.com/8057443/222685274-c9ef0e70-fd5d-48f7-a034-1389cb4e1e79.png)
