### ISSUE TITLE
Select list does not show list in the Record Rule 

### ISSUE THREAD

**Issue by wei9528** [digi-serve/plugin_ABDesigner#110]
**Describe the bug**
![status](https://user-images.githubusercontent.com/67583075/210511564-1cdc2b68-5aaf-4384-901e-c95cff3e2d08.png)

**Comment by wongpratan** [comment]
https://github.com/digi-serve/ab_platform_web/commit/3ccf7d634b9fcdff95099373f1d50138e0e5d0d5
https://github.com/digi-serve/plugin_ABDesigner/commit/d4a198a717252e07d73bece0c1ddfb6f55172a85
