### ISSUE TITLE
Unable to save Query task data

### ISSUE THREAD

**Issue by nh758** [digi-serve/plugin_ABDesigner#120]
Process is unable to save data in the Query task 
![Process](https://user-images.githubusercontent.com/67583075/210513371-cd7eedc3-66b2-4e5d-9ebb-c04779e0e5d5.png)

_Originally posted by @wei9528 in https://github.com/digi-serve/plugin_ABDesigner/issues/98#issuecomment-1370623117_

**Comment by wongpratan** [comment]
I could not reproduce it.

**Comment by wei9528** [comment]
Process Manger is updated, and the bug has been gone.
