### ISSUE TITLE
Unable to save page name

### ISSUE THREAD

**Issue by wei9528** [digi-serve/plugin_ABDesigner#122]
Staging2, MTF app, the page name Expense is changed to Home without knowing the reason, now it is unable to change it back. 
![Untitled](https://user-images.githubusercontent.com/67583075/213373840-bb89b2cf-11c2-499d-a7f5-4471df6c2c68.png)

**Comment by wongpratan** [comment]
I could not reproduce it. 

It might be the performance issue.
