### ISSUE TITLE
V2: unable to attach a picture

### ISSUE THREAD

**Issue by wei9528** [digi-serve/plugin_ABDesigner#129]
**To Reproduce**
1. Go to a form that contains an image field, click the Image field, no response.
![image](https://user-images.githubusercontent.com/67583075/216212739-7cfe7435-83e3-4575-8c79-e7a1dabceb71.png)
![receipt](https://user-images.githubusercontent.com/67583075/216214750-737b0fb3-4fc4-439f-9cfd-c2edd982d83d.png)

**Comment by jamesduncan** [comment]
I can confirm this bug. Looks like something has changed in how we identify the parent form...I will try to get a fix for this.

<img width="456" alt="Screen Shot 2023-02-02 at 12 02 09 PM" src="https://user-images.githubusercontent.com/106924/216236304-a72776eb-2856-44ed-9bfc-108d5005204b.png">

<img width="782" alt="Screen Shot 2023-02-02 at 12 02 35 PM" src="https://user-images.githubusercontent.com/106924/216236285-7127cc83-562d-46d1-b100-dd3a32627ef1.png">

**Comment by wei9528** [comment]
Fixed! Thanks James
