### ISSUE TITLE
V2: Image field is missing Property in the form widget

### ISSUE THREAD

**Issue by wei9528** [digi-serve/plugin_ABDesigner#133]
**To Reproduce**
1. Go to MTF > Add Donation form page, click Edit button in the Donation Receipt field, it still shows the Property panel of the form, instead of the field's property. 
<img width="767" alt="imagefield" src="https://user-images.githubusercontent.com/67583075/217991367-e48cb5d2-0605-47df-964c-3992ed2038c6.png">

**Comment by wongpratan** [comment]
https://github.com/digi-serve/ab_platform_web/commit/fd8b521e1cf994b7f348ae16183f75ec3016c195
