### ISSUE TITLE
Process Manager: unable to load connected fields

### ISSUE THREAD

**Issue by wei9528** [digi-serve/plugin_ABDesigner#135]
**Describe the bug**
Exists in V2 both PROD and Staging2

**To Reproduce**
1. Go to MTF > Expense Report Paid > select "Advance Clear JE" task, 
2. In the Report field, the default option is QX Center, and you are unable to change it to another object.
3. In the following field options, **Set by the instance[]** is missing instance name.
![P1](https://user-images.githubusercontent.com/67583075/218667002-ae2ceebf-ac35-41a9-9053-d9a6f336d0bb.png)

**Comment by wongpratan** [comment]
https://github.com/digi-serve/plugin_ABDesigner/commit/473c05b2312a8652bb0a3c84f65ed360cc30034d
