### ISSUE TITLE
Process Manager: unable to add a terminal event

### ISSUE THREAD

**Issue by wei9528** [digi-serve/plugin_ABDesigner#138]
**Describe the bug**
Found the bug on PROD
Click the terminal event, no response.
![pong](https://user-images.githubusercontent.com/67583075/219253530-e1c577b2-ed9a-4091-808f-6eebf36cf576.png)
![pong2](https://user-images.githubusercontent.com/67583075/219253542-f5d21b34-5575-416c-a802-9e2d3c4389ab.png)

**Comment by wongpratan** [comment]
Because the PROD site is using ab_platform_web#ns_app.
`ABProcess` does not have `unknownShape` function.
When #master will be ready and used, then it should solve this issue.
![end error](https://user-images.githubusercontent.com/545045/220364892-63cc6240-380a-4e83-af04-8cf34da1c3ba.png)
