### ISSUE TITLE
Issue after adding Filter for a Data Collection

### ISSUE THREAD

**Issue by wei9528** [digi-serve/plugin_ABDesigner#156]
**To Reproduce**
1. Go to staging2, AB Builder > Data Collection, try to add a filter for a DC.
2. The AB Designer will become a blank page, you have to reload the page
![DC](https://user-images.githubusercontent.com/67583075/222614681-e5e5d102-b84d-4939-ba9d-74c8d4cc59c3.png)

**Comment by jamesduncan** [comment]
Guy and I were looking at this the other day. It seems that if you have opened any page before opening the Designer then make a save to a datacollection the initial opened page reloads when the data collection is updated and the UI is pushed into the top of the screen above the Designer.

**Comment by jamesduncan** [comment]
From what I could tell this was a bug with webix...I can spend some time today trying to recreate the issue in webix snippets to confirm and verify it is an issue in the more current releases of webix as well.

**Comment by nh758** [comment]
Can no longer reproduce
