### ISSUE TITLE
Some queries do not show the data on the Queries section.

### ISSUE THREAD

**Issue by Tacchinardi20** [digi-serve/plugin_ABDesigner#198]
**Describe the bug**

The queries builder seem broken.
This is the example queries on FCF HR App of https://design.digiserve.org >>

**Screenshots**
![image](https://github.com/digi-serve/plugin_ABDesigner/assets/98794744/b4d2ee0b-8bac-4fe9-ba51-f4ff7485c6aa)
The data should show in the fields.
![image](https://github.com/digi-serve/plugin_ABDesigner/assets/98794744/6c288234-de1d-46c3-8046-c8e795e73398)

**Server**
https://design.digiserve.org

**Comment by nh758** [comment]
Needed to refresh the query, problem with mysql view
