### ISSUE TITLE
Connection data between the objects has lost when we clicked on the role of connected field in grid.

### ISSUE THREAD

**Issue by Tacchinardi20** [digi-serve/plugin_ABDesigner#242]
**Describe the bug**

In FCF HR App's AB Designer on design server, when we click on the role of HR / AP Person Profile Object which we want to change some data on the connected field. The connection data around that field which we want to change will lose too.

**To Reproduce**
1. Go to https://design.digiserve.org
2. Go to FCF HR App on AB Designer
3. Click on HR / AP Person Profile Object
4. Set Apply Sort to Last Name EN, so you can test this issue with our example "aaaa" person as in the picture.
![image](https://github.com/digi-serve/plugin_ABDesigner/assets/98794744/7220910e-c770-46ca-b9cc-25a1a42838ca)
5. Pick One example person "aaaa Cruise Tom"
6. Then move horizontal scroll to the connected field "Team Leader Of"
7. Then just try to click on the data of this connected field.
8. When you click out or even you don't want to change the data, anyway the data of connected field name "Contact" beside "Team Leader Of" will lose.
9. Actually it happed on others connected field in this object too, but these two object is easily to test and get the data back in.
10. Please see error on this clip
https://github.com/digi-serve/plugin_ABDesigner/assets/98794744/2ab1c326-145d-4302-aa01-240b92e983ec

**Server**

https://design.digiserve.org

**Comment by jamesduncan** [comment]
Prin and I were looking at this and it looks as if Webix has updated their logic to clear selected values when you run `theEditor.getList().clearAll();` therefore our code needs to be updated to store the initial selected value somewhere before we clear the list of options that way when we add them back we can reset the selected value.

<img width="1098" alt="Screenshot 2024-04-04 at 10 01 27 AM" src="https://github.com/digi-serve/plugin_ABDesigner/assets/106924/2c95e0d5-0238-4b56-a8cb-5a282ac6aea0">
