### ISSUE TITLE
Cursor is not set in FCF HR Address and Location DataCollections

### ISSUE THREAD

**Issue by jamesduncan** [digi-serve/plugin_ABDesigner#243]
**Describe the bug**
The Location and Address connected objects are not binding properly...or for some reason the cursor is not set properly.

**To Reproduce**
1. Go to https://design.digiserve.org/
2. Go to AB Designer
3. Go to FCF HR App
4. Go to Data Collections
5. Click on "HR Address-DC - Location-DC"
6. Try to change the set cursor above the records and there is not change in the resulting list.

**Expected behavior**
The list should filter to the matching records.

**Screenshots**
<img width="930" alt="Screenshot 2024-04-04 at 10 04 06 AM" src="https://github.com/digi-serve/plugin_ABDesigner/assets/106924/7f0da36d-9c72-4c5f-addd-de3c67928d43">

**Server**
Seen on https://design.digiserve.org/

**Additional context**
Something to note is after we clicked around and set the cursor on some other DataCollections and came back to this DataCollection the cursor was set properly and we were able to change it and it update the list correctly. We reloaded the site to try to reproduce and were unable to find what exact sequence we took to reproduce the results.

**Comment by Tacchinardi20** [comment]
I can solve this by select Load All. I will close this for now.
