### ISSUE TITLE
To Make the Date & Time Field Can Be Sorted

### ISSUE THREAD

**Issue by Tacchinardi20** [digi-serve/plugin_ABDesigner#266]
I think it would be great if we could sort by the Date & Time field because some apps need to use it for making sense.

In Example, I'm working on Hope App of https://design.digiserve.org

![Image](https://github.com/user-attachments/assets/e87d14e7-6978-4dd9-aab1-3c525b3bd02d)

![Image](https://github.com/user-attachments/assets/854b8200-82dc-4151-baec-7d6a699da5dd)

We cannot sort by the Date & Time field as in the picture.

![Image](https://github.com/user-attachments/assets/b2823044-f8d4-43fb-b1a7-630970ffea37)

Server :  All Server

**Comment by nh758** [comment]
Added in core [`v2.2.18`](https://github.com/digi-serve/appbuilder_class_core/releases/tag/v2.2.18).
