### ISSUE TITLE
List of Pages

### ISSUE THREAD

**Issue by nh758** [digi-serve/plugin_ABDesigner#3]
## Requirements
1. I can see a list of Pages
2. I can add a new page
    - I can select which page is the parent 
3. I can rename and delete

### Tasks
- [x] See list
- [x] Acces page options
- - [x] Rename 
- - [x] Delete
- - [x] Copy
- [x] Add new page
- - [x] Select parent page
- [ ] Write Documentation

**Comment by Achoobert** [comment]
'quick page' feature was not added, I think that will involve adding widgets based on objects to subpages, and so needs to be added later on when widgets are accessible
