### ISSUE TITLE
UI Mockup: App Settings

### ISSUE THREAD

**Issue by nh758** [digi-serve/plugin_ABDesigner#41]
## Requirements
1. A Webix Snippet with a Mock up UI for the Query Task

### Tasks
- [ ] Write Documentation

## Reference
Current UI
![image](https://user-images.githubusercontent.com/10155226/177704217-4003eca9-a9b1-4eaf-8830-9edb00fcc6d1.png)

Can create on: https://snippet.webix.com/basic

#### Suggestions: 
- Make it a popup not a page
- Icon should be a dropdown list, not text
- Subheadings standout too much

**Comment by Tacchinardi20** [comment]
Please Review  :)

https://snippet.webix.com/2nfa8uux

**Comment by Tacchinardi20** [comment]
https://snippet.webix.com/4sy0q5sv

Updated Design

**Comment by nh758** [comment]
Cool, looks good.

**Comment by Tacchinardi20** [comment]
Thanks, Nathan
